import type { Collection, Product } from './types'

/**
 * The coffee catalogue. Hand-authored rather than generated, because the
 * tasting notes and origin stories are what make the storefront look like a
 * real roastery rather than a lorem-ipsum grid.
 *
 * Prices are integer cents. `bags()` derives the 500g and 1kg variants from
 * the 250g price so the tiers stay consistent across the catalogue.
 */

function bags(
  slug: string,
  base250: number,
  stock: [number, number, number],
  compareAt250?: number,
) {
  return [
    {
      id: `${slug}-250`,
      size: '250g' as const,
      priceCents: base250,
      compareAtCents: compareAt250,
      stock: stock[0],
    },
    {
      id: `${slug}-500`,
      size: '500g' as const,
      priceCents: Math.round((base250 * 1.85) / 50) * 50,
      stock: stock[1],
    },
    {
      id: `${slug}-1kg`,
      size: '1kg' as const,
      priceCents: Math.round((base250 * 3.4) / 50) * 50,
      stock: stock[2],
    },
  ]
}

export const collections: Collection[] = [
  {
    id: 'col-single-origin',
    slug: 'single-origin',
    title: 'Single origin',
    description:
      'One farm, one lot, one harvest. Bought on relationship, roasted to show what the origin actually tastes like.',
  },
  {
    id: 'col-blends',
    slug: 'blends',
    title: 'Blends',
    description:
      'Built for repeatability. The same cup on a Tuesday in March as on a Sunday in November.',
  },
  {
    id: 'col-espresso',
    slug: 'espresso',
    title: 'Espresso',
    description: 'Roasted a touch further and rested longer, so they pull sweet under pressure.',
  },
  {
    id: 'col-filter',
    slug: 'filter',
    title: 'Filter',
    description: 'Lighter roasts with the acidity left intact. Pour-over, batch brew, immersion.',
  },
  {
    id: 'col-decaf',
    slug: 'decaf',
    title: 'Decaf',
    description: 'Sugarcane EA decaffeination only. No solvents, no flattened fruit.',
  },
  {
    id: 'col-limited',
    slug: 'limited',
    title: 'Limited release',
    description: 'Micro-lots and competition coffees. When they are gone, they are gone.',
  },
]

export const products: Product[] = [
  {
    id: 'p-guji',
    slug: 'ethiopia-guji-uraga',
    name: 'Guji Uraga',
    origin: 'Ethiopia',
    region: 'Guji, Uraga',
    producer: 'Uraga Washing Station',
    altitudeMeters: 2150,
    varietal: 'Heirloom',
    process: 'natural',
    roast: 'light',
    tastingNotes: ['Blueberry', 'Jasmine', 'Dark chocolate', 'Lime zest'],
    blurb: 'A natural Ethiopian that tastes like blueberry jam without giving up the florals.',
    story:
      'Uraga sits high enough that cherries ripen slowly, and the station dries them on raised beds for eighteen days with hourly turning. That patience is why this lot reads as clean fruit rather than ferment. We roast it light enough to keep the jasmine intact, which means it wants a slightly finer grind than you are probably used to.',
    brewMethods: ['whole-bean', 'filter', 'french-press'],
    variants: bags('guji', 2250, [42, 18, 6]),
    rating: 4.8,
    reviewCount: 214,
    releasedOn: '2026-07-14',
    featured: true,
    limitedRelease: false,
    collections: ['single-origin', 'filter'],
  },
  {
    id: 'p-huila',
    slug: 'colombia-huila-pitalito',
    name: 'Huila Pitalito',
    origin: 'Colombia',
    region: 'Huila, Pitalito',
    producer: 'Finca El Mirador — Yesenia Ramírez',
    altitudeMeters: 1780,
    varietal: 'Pink Bourbon',
    process: 'washed',
    roast: 'medium',
    tastingNotes: ['Red apple', 'Panela', 'Orange blossom'],
    blurb: 'Pink Bourbon grown by a third-generation producer. Sweet, structured, endlessly drinkable.',
    story:
      'Yesenia took over El Mirador in 2019 and replanted two hectares to Pink Bourbon against every piece of advice she was given. Six harvests later it is the lot we buy first every year. Ferments run 36 hours in sealed tanks before a clean wash and twelve days on the patio.',
    brewMethods: ['whole-bean', 'filter', 'espresso'],
    variants: bags('huila', 1950, [64, 31, 12]),
    rating: 4.7,
    reviewCount: 356,
    releasedOn: '2026-06-02',
    featured: true,
    limitedRelease: false,
    collections: ['single-origin', 'filter', 'espresso'],
  },
  {
    id: 'p-nightshift',
    slug: 'night-shift-espresso',
    name: 'Night Shift',
    origin: 'Blend',
    region: 'Brazil, Colombia, India',
    producer: 'Multiple producers',
    altitudeMeters: 1400,
    varietal: 'Catuaí, Castillo, Robusta',
    process: 'natural',
    roast: 'medium-dark',
    tastingNotes: ['Cocoa nib', 'Toasted hazelnut', 'Brown sugar'],
    blurb: 'Our house espresso. Built to hold its shape through milk at any volume.',
    story:
      'Three components, each doing one job. Brazilian Catuaí for body, Colombian Castillo for sweetness and a small percentage of washed Indian Robusta for the crema and the caffeine kick that a 6am shift actually needs. Rested ten days before it ships.',
    brewMethods: ['whole-bean', 'espresso', 'moka'],
    variants: bags('nightshift', 1750, [120, 88, 54]),
    rating: 4.6,
    reviewCount: 892,
    releasedOn: '2025-01-20',
    featured: true,
    limitedRelease: false,
    collections: ['blends', 'espresso'],
  },
  {
    id: 'p-kirinyaga',
    slug: 'kenya-kirinyaga-ak',
    name: 'Kirinyaga AA',
    origin: 'Kenya',
    region: 'Kirinyaga',
    producer: 'Kianjuki Factory',
    altitudeMeters: 1850,
    varietal: 'SL28, SL34, Ruiru 11',
    process: 'washed',
    roast: 'light',
    tastingNotes: ['Blackcurrant', 'Tomato leaf', 'Grapefruit', 'Cane sugar'],
    blurb: 'The blackcurrant-and-grapefruit Kenyan that ruins other coffees for you.',
    story:
      'Kianjuki takes cherry from around 900 smallholders and still manages a strict double ferment with clean water from the Ragati river. The SL28 does the heavy lifting here: an acidity so structural it feels almost carbonated. Do not brew this hot.',
    brewMethods: ['whole-bean', 'filter'],
    variants: bags('kirinyaga', 2450, [24, 9, 0]),
    rating: 4.9,
    reviewCount: 178,
    releasedOn: '2026-08-08',
    featured: true,
    limitedRelease: true,
    collections: ['single-origin', 'filter', 'limited'],
  },
  {
    id: 'p-antigua',
    slug: 'guatemala-antigua-bella-vista',
    name: 'Antigua Bella Vista',
    origin: 'Guatemala',
    region: 'Antigua',
    producer: 'Finca Bella Vista',
    altitudeMeters: 1600,
    varietal: 'Bourbon, Caturra',
    process: 'washed',
    roast: 'medium',
    tastingNotes: ['Milk chocolate', 'Baked pear', 'Almond'],
    blurb: 'Volcanic soil, classic Antigua profile. The coffee to hand someone who says they hate coffee.',
    story:
      'Grown in pumice-rich soil between three volcanoes, which holds water through the dry season and gives Antigua coffees their particular density. Bella Vista shades its lots under gravilea, slowing maturation by nearly three weeks compared to neighbouring farms.',
    brewMethods: ['whole-bean', 'filter', 'espresso', 'french-press'],
    variants: bags('antigua', 1850, [88, 40, 19]),
    rating: 4.5,
    reviewCount: 411,
    releasedOn: '2026-05-19',
    featured: false,
    limitedRelease: false,
    collections: ['single-origin', 'espresso'],
  },
  {
    id: 'p-sumatra',
    slug: 'sumatra-lintong-blue-batak',
    name: 'Lintong Blue Batak',
    origin: 'Indonesia',
    region: 'Sumatra, Lintong',
    producer: 'Batak smallholder collective',
    altitudeMeters: 1450,
    varietal: 'Typica, Ateng',
    process: 'honey',
    roast: 'dark',
    tastingNotes: ['Cedar', 'Molasses', 'Dried fig', 'Black pepper'],
    blurb: 'Wet-hulled and unapologetic. Earthy, syrupy and enormous in a French press.',
    story:
      'Wet hulling is a Sumatran invention born of humidity — the parchment comes off at a much higher moisture content, which is exactly where the cedar and pepper notes come from. This lot is a cleaner take than most, with the collective sorting three times before export.',
    brewMethods: ['whole-bean', 'french-press', 'moka'],
    variants: bags('sumatra', 2050, [31, 14, 5]),
    rating: 4.3,
    reviewCount: 267,
    releasedOn: '2026-03-11',
    featured: false,
    limitedRelease: false,
    collections: ['single-origin'],
  },
  {
    id: 'p-firstlight',
    slug: 'first-light-breakfast-blend',
    name: 'First Light',
    origin: 'Blend',
    region: 'Colombia, Guatemala',
    producer: 'Multiple producers',
    altitudeMeters: 1650,
    varietal: 'Castillo, Bourbon',
    process: 'washed',
    roast: 'medium',
    tastingNotes: ['Caramel', 'Golden raisin', 'Cashew'],
    blurb: 'The batch-brew blend. Forgiving, sweet, and good at any strength.',
    story:
      'Designed backwards from a bad hotel-room brewer. If a coffee still tastes sweet at a 1:18 ratio with lukewarm water and a paper filter that has been in the drawer too long, it will taste extraordinary when you do everything right.',
    brewMethods: ['whole-bean', 'filter', 'french-press'],
    variants: bags('firstlight', 1650, [140, 96, 72]),
    rating: 4.4,
    reviewCount: 1043,
    releasedOn: '2024-09-05',
    featured: false,
    limitedRelease: false,
    collections: ['blends', 'filter'],
  },
  {
    id: 'p-decaf',
    slug: 'colombia-decaf-sugarcane',
    name: 'Quiet Hours Decaf',
    origin: 'Colombia',
    region: 'Huila',
    producer: 'Descafecol, Manizales',
    altitudeMeters: 1700,
    varietal: 'Castillo',
    process: 'washed',
    roast: 'medium',
    tastingNotes: ['Dark cherry', 'Cocoa', 'Malt'],
    blurb: 'Sugarcane EA decaf that still tastes like the coffee it came from.',
    story:
      'Ethyl acetate derived from fermented sugarcane, produced twenty minutes from where the coffee was grown. It removes caffeine without the pressure and heat cycles that flatten fruit in the CO2 process. Genuinely good at 9pm.',
    brewMethods: ['whole-bean', 'filter', 'espresso'],
    variants: bags('decaf', 1950, [56, 22, 8]),
    rating: 4.5,
    reviewCount: 189,
    releasedOn: '2026-04-27',
    featured: false,
    limitedRelease: false,
    collections: ['decaf', 'filter'],
  },
  {
    id: 'p-nariño',
    slug: 'colombia-narino-anaerobic',
    name: 'Nariño Anaerobic',
    origin: 'Colombia',
    region: 'Nariño, Buesaco',
    producer: 'Wilton Benítez',
    altitudeMeters: 1950,
    varietal: 'Caturra',
    process: 'anaerobic',
    roast: 'light',
    tastingNotes: ['Lychee', 'Rose', 'Passionfruit', 'Green tea'],
    blurb: 'A 120-hour sealed ferment. Tastes less like coffee than like a very good cocktail.',
    story:
      'Benítez controls pH and temperature hourly through a five-day anaerobic ferment, then dries under shade for twenty-two days. The result is polarising and we love it: if you have never had a coffee that tastes floral to the point of perfume, start here.',
    brewMethods: ['whole-bean', 'filter'],
    variants: bags('narino', 3200, [12, 4, 0]),
    rating: 4.7,
    reviewCount: 76,
    releasedOn: '2026-08-21',
    featured: true,
    limitedRelease: true,
    collections: ['single-origin', 'limited', 'filter'],
  },
  {
    id: 'p-yirgacheffe',
    slug: 'ethiopia-yirgacheffe-kochere',
    name: 'Yirgacheffe Kochere',
    origin: 'Ethiopia',
    region: 'Yirgacheffe, Kochere',
    producer: 'Kochere Cooperative',
    altitudeMeters: 2000,
    varietal: 'Heirloom',
    process: 'washed',
    roast: 'light',
    tastingNotes: ['Bergamot', 'Peach', 'Honeysuckle'],
    blurb: 'The washed Ethiopian benchmark. Tea-like, delicate, and impossible to get bored of.',
    story:
      'Where the naturals from Guji shout, Kochere washed lots whisper. Fermented in clean water for 48 hours and washed through grading channels, this is the profile that taught most of us what acidity actually means.',
    brewMethods: ['whole-bean', 'filter'],
    variants: bags('yirgacheffe', 2150, [48, 26, 11]),
    rating: 4.8,
    reviewCount: 302,
    releasedOn: '2026-07-01',
    featured: false,
    limitedRelease: false,
    collections: ['single-origin', 'filter'],
  },
  {
    id: 'p-brazil',
    slug: 'brazil-cerrado-fazenda-rainha',
    name: 'Cerrado Fazenda Rainha',
    origin: 'Brazil',
    region: 'Cerrado Mineiro',
    producer: 'Fazenda Rainha',
    altitudeMeters: 1100,
    varietal: 'Yellow Catuaí',
    process: 'natural',
    roast: 'medium-dark',
    tastingNotes: ['Peanut brittle', 'Milk chocolate', 'Vanilla'],
    blurb: 'Low acidity, huge body. The best-value bag we sell and the one we drink most at home.',
    story:
      'Mechanically harvested at scale and none the worse for it — Rainha is one of the few large farms whose cup quality holds up lot after lot. Dried on concrete patios in thin layers, turned four times a day.',
    brewMethods: ['whole-bean', 'espresso', 'moka', 'french-press'],
    variants: bags('brazil', 1450, [180, 120, 90]),
    rating: 4.2,
    reviewCount: 528,
    releasedOn: '2026-02-14',
    featured: false,
    limitedRelease: false,
    collections: ['single-origin', 'espresso', 'blends'],
  },
  {
    id: 'p-costarica',
    slug: 'costa-rica-tarrazu-honey',
    name: 'Tarrazú Honey',
    origin: 'Costa Rica',
    region: 'Tarrazú, Los Santos',
    producer: 'Beneficio Don Eli',
    altitudeMeters: 1720,
    varietal: 'Villa Sarchí',
    process: 'honey',
    roast: 'medium',
    tastingNotes: ['Apricot', 'Honeycomb', 'Toffee'],
    blurb: 'Yellow honey process with the mucilage left on just long enough to matter.',
    story:
      'Don Eli leaves roughly forty percent of the mucilage on the bean and dries slowly under shade nets for sixteen days. It is a narrow window — a day too long and it tastes like ferment, a day too short and you have a washed coffee. This lot landed it.',
    brewMethods: ['whole-bean', 'filter', 'espresso'],
    variants: bags('costarica', 2250, [37, 16, 0]),
    rating: 4.6,
    reviewCount: 144,
    releasedOn: '2026-06-25',
    featured: false,
    limitedRelease: false,
    collections: ['single-origin', 'filter'],
  },
  {
    id: 'p-slowburn',
    slug: 'slow-burn-dark-roast',
    name: 'Slow Burn',
    origin: 'Blend',
    region: 'Sumatra, Brazil',
    producer: 'Multiple producers',
    altitudeMeters: 1300,
    varietal: 'Ateng, Catuaí',
    process: 'natural',
    roast: 'dark',
    tastingNotes: ['Bittersweet chocolate', 'Pipe tobacco', 'Black walnut'],
    blurb: 'For anyone who thinks third wave roasting went too light. No apologies.',
    story:
      'Taken to the edge of second crack and stopped, which is a much harder roast to execute than a light one. Half Sumatran wet-hulled for the earthy backbone, half Brazilian natural to keep sweetness in the cup rather than just char.',
    brewMethods: ['whole-bean', 'french-press', 'moka', 'espresso'],
    variants: bags('slowburn', 1550, [92, 61, 40]),
    rating: 4.1,
    reviewCount: 386,
    releasedOn: '2025-11-08',
    featured: false,
    limitedRelease: false,
    collections: ['blends'],
  },
  {
    id: 'p-panama',
    slug: 'panama-boquete-geisha',
    name: 'Boquete Geisha',
    origin: 'Panama',
    region: 'Boquete, Chiriquí',
    producer: 'Hacienda La Esmeralda',
    altitudeMeters: 1650,
    varietal: 'Geisha',
    process: 'washed',
    roast: 'light',
    tastingNotes: ['Jasmine', 'Bergamot', 'White peach', 'Cane sugar'],
    blurb: 'The coffee that reset the ceiling on what green coffee can cost. Worth it once.',
    story:
      'Twenty-two grams of some of the most sought-after coffee grown anywhere, from the farm that introduced Geisha to the specialty market in 2004. We buy a handful of kilos a year and sell it in 100g bags because pretending otherwise would be dishonest. Brew it gently and pay attention.',
    brewMethods: ['whole-bean', 'filter'],
    variants: bags('panama', 6800, [8, 0, 0]),
    rating: 4.9,
    reviewCount: 41,
    releasedOn: '2026-08-24',
    featured: false,
    limitedRelease: true,
    collections: ['single-origin', 'limited', 'filter'],
  },
]

export const productBySlug = new Map(products.map((product) => [product.slug, product]))
export const productById = new Map(products.map((product) => [product.id, product]))
